### ISSUE TITLE
enmetric unit tests failing on armel, armhf

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#545]
On 32-bit soft-float ARM, we're blowing up in the `PowersOfTenMinusOne` unit test. See Debian's buildd for more information: https://buildd.debian.org/status/fetch.php?pkg=notcurses&arch=armel&ver=1.3.3%2Bdfsg.1-1&stamp=1587957612&raw=0.

Likewise, this same failure is happening for armhf (32-bit hard float ARMv7). Most other failures I'm seeing are due to #543 .

```
===============================================================================
/<<PKGBUILDDIR>>/tests/metric.cpp:22:
TEST CASE:  ncmetric
  PowersOfTenMinusOne

/<<PKGBUILDDIR>>/tests/metric.cpp:261: ERROR: CHECK( !strcmp(gold, buf) ) is NOT correct!
  values: CHECK( false )

/<<PKGBUILDDIR>>/tests/metric.cpp:261: ERROR: CHECK( !strcmp(gold, buf) ) is NOT correct!
  values: CHECK( false )

/<<PKGBUILDDIR>>/tests/metric.cpp:261: ERROR: CHECK( !strcmp(gold, buf) ) is NOT correct!
  values: CHECK( false )

/<<PKGBUILDDIR>>/tests/metric.cpp:261: ERROR: CHECK( !strcmp(gold, buf) ) is NOT correct!
  values: CHECK( false )

===============================================================================
[doctest] test cases:     37 |     36 passed |      1 failed |      1 skipped
[doctest] assertions: 8343139 | 8343135 passed |      4 failed |
[doctest] Status: FAILURE!
```

**Comment by dankamongmen** [comment]
I think this might be best remedied by moving to `snprintf()` as long considered, and restricting ourselves to prefixing. It probably performs better, anyway (especially as we make at least one `snprintf(3)` call anyway).

**Comment by dankamongmen** [comment]
I migrated our more involved calculations to `%.2f`, and was able to eliminate the `pthread_once` with which we checked `localeconv()`. I think that'll get this.
