### PR TITLE
CMake: find homebrew deps on OS X #1933

### PR DESCRIPTION
**Pull request by dankamongmen**
I don't love it, but it does seem to work. For lack of a better solution, define the environment variable `PKG_CONFIG_PATH` for OS X in CMake to point at the necessary `/usr/local` entries.

We should probably concatenate with any existing definition, or perhaps simply not change an existing definition.

### CODE REVIEW

**Comment by dankamongmen** [comment]
i changed it up to defer to an existing `PKG_CONFIG_PATH` environment variable if one exists.

**Comment by michaelsbradleyjr** [comment]
I just tried it locally (on my laptop instead of the Mac mini, the former is running macOS 10.15 while the latter is running latest).

`cmake` complete successfully, but I encountered errors with `make`:
```
[ 87%] Building CXX object CMakeFiles/notcurses-tester.dir/src/tests/Exceptions.cpp.o
In file included from /Users/michael/repos/forks/notcurses/src/tests/Exceptions.cpp:2:
In file included from /Users/michael/repos/forks/notcurses/src/tests/main.h:12:
/Users/michael/repos/forks/notcurses/src/lib/internal.h:1033:19: error: use of undeclared identifier
      'POLLOUT'
        .events = POLLOUT,
                  ^
/Users/michael/repos/forks/notcurses/src/lib/internal.h:1031:21: error: variable has incomplete type
      'struct pollfd'
      struct pollfd pfd = {
                    ^
/Users/michael/repos/forks/notcurses/src/lib/internal.h:1031:14: note: forward declaration of
      'pollfd'
      struct pollfd pfd = {
             ^
2 errors generated.
make[2]: *** [CMakeFiles/notcurses-tester.dir/src/tests/Exceptions.cpp.o] Error 1
make[1]: *** [CMakeFiles/notcurses-tester.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by michaelsbradleyjr** [comment]
I tried on the Mac mini (macOS 11.4) and didn't get the error; will try to figure out why it's failing on my laptop.

**Comment by dankamongmen** [comment]
possibly related to recent `poll.h` include move for windows?

**Comment by michaelsbradleyjr** [comment]
> possibly related to recent `poll.h` include move for windows?

I'm not sure yet. But it seems strange to that the `make` step works in GHA, which is running macOS 10.15.7, just like my laptop, but fails on my laptop. There must be a difference re: the versions of Xcode stuff and/or the versions of things installed via `brew`, though I updated all my brew packages locally and `make` is still failing.

I'm a bit pressed for time atm, but will continue the investigation as I'm able.

**Comment by dankamongmen** [comment]
> I'm not sure yet. But it seems strange to that the `make` step works in GHA, which is running macOS 10.15.7, just like my laptop, but fails on my laptop. There must be a difference re: the versions of Xcode stuff and/or the versions of things installed via `brew`, though I updated all my brew packages locally and `make` is still failing.
> 
> I'm a bit pressed for time atm, but will continue investigating when possible.

.nodnod i agree the failure is worth resolving, and this can certainly sit until it's more perfect. also, i went and looked, and am pretty certain the change i mentioned oughtn't have had any effect.

**Comment by michaelsbradleyjr** [comment]
I tried rebasing this branch against `master` locally on my mac laptop, and `make` failed roughly the same way:

```
[ 11%] Building C object CMakeFiles/notcurses-core.dir/src/lib/blit.c.o
In file included from /Users/michael/repos/forks/notcurses/src/lib/blit.c:3:
/Users/michael/repos/forks/notcurses/src/lib/internal.h:1040:19: error: use of undeclared identifier
      'POLLOUT'
        .events = POLLOUT,
                  ^
/Users/michael/repos/forks/notcurses/src/lib/internal.h:1038:21: error: variable has incomplete type
      'struct pollfd'
      struct pollfd pfd = {
                    ^
/Users/michael/repos/forks/notcurses/src/lib/internal.h:1038:14: note: forward declaration of
      'struct pollfd'
      struct pollfd pfd = {
             ^
/Users/michael/repos/forks/notcurses/src/lib/internal.h:1043:7: error: implicit declaration of
      function 'poll' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      poll(&pfd, 1, -1);
      ^
/Users/michael/repos/forks/notcurses/src/lib/blit.c:1041:75: warning: format specifies type
      'unsigned long long' but the argument has type 'uintmax_t' (aka 'unsigned long') [-Wformat]
    fprintf(stderr, "Warning: unknown ncvisual options %016" PRIx64 "\n", (uintmax_t)vopts->flags);
                                                       ~~~~~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~
1 warning and 3 errors generated.
make[2]: *** [CMakeFiles/notcurses-core.dir/src/lib/blit.c.o] Error 1
make[1]: *** [CMakeFiles/notcurses-core.dir/all] Error 2
make: *** [all] Error 2
```

Note: `error: implicit declaration of function 'poll' is invalid in C99`.

Searching around, it seems other people have run into similar problems building other software on macOS, depending on the version of Xcode; but I couldn't find a real answer or solution to what's going on.

So then I switched to current `master`, exported `PKG_CONFIG_PATH` as before, and building it fails the same way!

I'm very confused as to what could be going on. Also, to make matters more confusing, I checked what `cmake` reports on macOS in GHA and also the documentation for what's installed in that GHA environment. Everything is an exact match for my local laptop. Seriously, WTF?

Just for fun, I tried adding `#include <poll.h>` near the top of `src/lib/internal.h` and that results in `make` failing much later. Again, this is on current `master`:

```
[ 58%] Building CXX object CMakeFiles/ncplayer.dir/src/player/play.cpp.o
/Users/michael/repos/forks/notcurses/src/player/play.cpp:121:18: warning: format specifies type
      'long long' but the argument has type 'intmax_t' (aka 'long') [-Wformat]
                 h, m, s, ns / 1000000);
                 ^
/Users/michael/repos/forks/notcurses/src/player/play.cpp:121:21: warning: format specifies type
      'long long' but the argument has type 'intmax_t' (aka 'long') [-Wformat]
                 h, m, s, ns / 1000000);
                    ^
/Users/michael/repos/forks/notcurses/src/player/play.cpp:121:24: warning: format specifies type
      'long long' but the argument has type 'intmax_t' (aka 'long') [-Wformat]
                 h, m, s, ns / 1000000);
                       ^
/Users/michael/repos/forks/notcurses/src/player/play.cpp:121:27: warning: format specifies type
      'long long' but the argument has type 'long' [-Wformat]
                 h, m, s, ns / 1000000);
                          ^~~~~~~~~~~~
/Users/michael/repos/forks/notcurses/src/player/play.cpp:334:10: error: no matching constructor for
      initialization of 'ncpp::Direct'
  Direct dm{nullptr, nullptr, flags};
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/ncpp/Direct.hh:19:12: note: candidate constructor not viable: no known conversion
      from 'uint64_t' (aka 'unsigned long long') to 'ncpp::NotCurses *' for 3rd argument
                explicit Direct (const char *termtype = nullptr, FILE *fp = nullptr, NotCurse...
                         ^
/usr/local/include/ncpp/Direct.hh:16:24: note: candidate constructor (the implicit copy constructor)
      not viable: requires 1 argument, but 3 were provided
        class NCPP_API_EXPORT Direct : public Root
                              ^
4 warnings and 1 error generated.
make[2]: *** [CMakeFiles/ncplayer.dir/src/player/play.cpp.o] Error 1
make[1]: *** [CMakeFiles/ncplayer.dir/all] Error 2
make: *** [all] Error 2
```

I then switched back to rebased `dankamongmen/osx-pkgconfig`, did a `git clean -dfx`, unset `PKG_CONFIG_PATH`, applied the same change re: `<poll.h>, ran `cmake` and `make` and it failed in the exact same way.

So... I don't think there's any problem with this PR, and I think you can go ahead and merge it.

On the other hand, I have absolutely no clue what's going wrong when building on my mac laptop.

**Comment by dankamongmen** [comment]
you shouldn't need be exporting `PKG_CONFIG_PATH` anymore, btw--i tucked that into `CMakeLists.txt`.
